version: '3'

networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpline
    ports:
      - "80:80" 
    depends_on:
      - frontend
    
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    networks:
      - dev

  frontend:
    build: .
    networks:
      - dev