version: '3'

networks:
  dev:

services:
  proxy: 
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always

  app:
    build: .
