# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ExpCurvFitting/ExpCurvFitting/ExpCurvFitting.sln 
    - name: Build
      run: dotnet build --no-restore ExpCurvFitting/ExpCurvFitting/ExpCurvFitting.sln 
    - name: Test
      run: dotnet test --no-build ExpCurvFitting/ExpCurvFitting/ExpCurvFitting.sln 
